#!/bin/bash

# ChatSyncro Backend Setup Script
# This script helps you set up the backend server with your Discord bot token

echo "======================================"
echo "ChatSyncro Backend Setup"
echo "======================================"
echo ""

# Check if .env file already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    echo "Remove it first if you want to reconfigure:"
    echo "rm .env"
    exit 1
fi

# Get Discord Token
echo "🤖 Discord Bot Setup"
echo "==================="
echo ""
echo "To get your Discord bot token:"
echo "1. Go to https://discord.com/developers/applications"
echo "2. Create or select your application"
echo "3. Go to 'Bot' section"
echo "4. Copy the TOKEN"
echo ""
read -p "Enter your Discord bot token: " DISCORD_TOKEN

if [ -z "$DISCORD_TOKEN" ]; then
    echo "❌ Token cannot be empty!"
    exit 1
fi

# Get Channel ID
echo ""
echo "📝 Discord Channel Setup"
echo "======================="
echo ""
echo "To get your channel ID:"
echo "1. Enable Developer Mode in Discord (Settings > App Settings > Advanced)"
echo "2. Right-click on the channel"
echo "3. Click 'Copy Channel ID'"
echo ""
read -p "Enter your Discord channel ID: " CHANNEL_ID

if [ -z "$CHANNEL_ID" ]; then
    echo "❌ Channel ID cannot be empty!"
    exit 1
fi

# Get Port (optional)
echo ""
read -p "Enter port number (default 3000): " PORT
PORT=${PORT:-3000}

# Create .env file
cat > .env << EOF
# ChatSyncro Backend Environment Configuration
# Generated by setup script

DISCORD_TOKEN=$DISCORD_TOKEN
CHANNEL_ID=$CHANNEL_ID
PORT=$PORT
NODE_ENV=production
EOF

echo ""
echo "✅ Configuration saved to .env file!"
echo ""
echo "📋 Your settings:"
echo "   Channel ID: $CHANNEL_ID"
echo "   Port: $PORT"
echo ""
echo "🔒 Discord Token: ***${DISCORD_TOKEN: -10}"
echo ""
echo "⚠️  NEVER share your .env file or token!"
echo ""
echo "🚀 Next steps:"
echo "   1. npm install"
echo "   2. npm start"
echo ""
echo "======================================"
